Feat/mobility
ONDC-Official/log-validation-utility pull request #20
Opened 2024-01-04 05:14 UTC by sourabhsaini11

2024-01-05 08:06 UTC, bluecypher commented on constants/index.ts
> +  FIS_SEARCH: 'search',
Pls merge the constants with same values. eg RET_SEARCH, FIS_SEARCH, MOB_SEARCH and replace it across all the files

2024-01-05 08:12 UTC, bluecypher commented on controller/validate/index.ts
> +          case '1.2.0':
This switch case is for retail version 1.2.0. pls utilize the validate function itself and accommodate all the domains there

2024-01-05 09:14 UTC, bluecypher requested changes
Can you please fix the issues

2024-01-08 12:03 UTC, sourabhsaini11 commented
@bluecypher above comments are resolved, kindly review

2024-01-08 12:42 UTC, bluecypher requested changes
package-lock.json and .DS_Store files should be a part of gitignore and not to be uploaded on GitHub. Please check the feat/phase2 branch for such minor fixes

2024-01-08 16:22 UTC, merged